backend:
  name: github
  repo: danica-books/danica-books
  branch: main
  auth_type: pkce
  base_url: https://decap-oauth-proxy.netlify.app
  auth_endpoint: auth
  cms_label_prefix: "Danica Books"

media_folder: "images"
public_folder: "/danica-books/images"

collections:
  - name: "books"
    label: "Könyvek"
    folder: "data/books"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Leírás", name: "description", widget: "text" }
      - { label: "Borító", name: "cover", widget: "image" }
      - { label: "Letöltési link", name: "download", widget: "string" }
