backend:
  name: github
  repo: danica-books/danica-books
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "books"
    label: "Könyvek"
    folder: "data/books"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    slug_encoding: "ascii"
    slug_clean_accents: true
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Leírás", name: "description", widget: "text" }
      - { label: "Borító", name: "cover", widget: "image" }
      - { label: "Letöltési link", name: "download", widget: "string" }
